# Generated by Django 4.2.1 on 2023-05-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_blog_options_alter_blog_count_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='count_views',
            field=models.IntegerField(default='0', verbose_name='Количество просмотров'),
        ),
    ]
