# Generated by Django 4.2.2 on 2023-06-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_product_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_publication',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Опубликовано'),
        ),
    ]
