# Generated by Django 4.2.2 on 2023-06-13 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_product_is_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_publication',
            new_name='is_publicate',
        ),
    ]
