# Generated by Django 4.2.2 on 2023-06-19 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('name',), 'verbose_name': 'версия', 'verbose_name_plural': 'версии'},
        ),
        migrations.RenameField(
            model_name='version',
            old_name='current_version',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(max_length=150, verbose_name='название версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='number',
            field=models.CharField(max_length=50, verbose_name='номер версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='продукт'),
        ),
    ]
